apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: 724772049461.dkr.ecr.us-west-2.amazonaws.com/web-app:latest
          ports:
            - containerPort: 3000
